site_name: Issue Project
site_url: https://gustjd887.github.io
repo_url: https://github.com/gustjd887
edit_uri: ""
# copyright: Copyright &copy; 2019 - 2020 gustjd887
theme:
  name: material
  language: kr
  palette:
    scheme: slate
  # features:
  #   - navigation.tabs
nav:
  - 홈: index.md
  - 개발:
    - Issue Site: Development 487bbf9393154af59112f13193012e32/Issue Site a8cfdacdda3044e68a16ea195673d2e5.md
    - Issue Collector: Development 487bbf9393154af59112f13193012e32/Issue Collector 4f53281392da417f9473e6b2e909e1f2.md
    - Issue Admin: Development 487bbf9393154af59112f13193012e32/Issue Admin a0ba9f16fbf049f3b684ae5a596cf13a.md
  - 배포:
    - Gitlab : Deploy ce570c6eea7d4b19a2c84703d0134c3a/Gitlab 1143fa2fc3214f7ebf7fb75bc642865f.md
    - Github: Deploy ce570c6eea7d4b19a2c84703d0134c3a\GIthub b7f48d0d71b24a4aba01de217ab5a5b8.md
  - 서비스:
    - Kubernetes: Service dcf013b07d0746eb84605d38ef7e98b3/Kubernetes 9ee16a8448ab4aaa87abd0a288d01a20.md
    - AWS: Service dcf013b07d0746eb84605d38ef7e98b3/AWS e7393387e6a24494b9bde2961ca3fed2.md
    - Docker: Service dcf013b07d0746eb84605d38ef7e98b3/Docker Compose 12d1029832874e1ca28062904fd2caad.md
extra:
  social:
    - icon: fontawesome/solid/blog
      link: https://gustjd887.tistory.com
      name: Tistory Blog
    - icon: fontawesome/regular/window-maximize
      link: http://issue.xu4.zz.am
      name: Project Site
    - icon: fontawesome/brands/github
      link: https://github.com/gustjd887
      name: Github
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/gustjd887
      name: Docker hub
    - icon: fontawesome/solid/certificate
      link: https://www.youracclaim.com/users/hyeonseong-park/badges
      name: Certificate
    - icon: fontawesome/solid/paper-plane
      link: mailto:gustjd887@gmail.com
      name: Email