site_name: 삽질하는 고슴도치
site_url: https://gustjd887.github.io
theme:
  name: material
  language: kr
  features:
    - tabs
  palette:
    scheme: slate
# extra:
#   disqus: gustjd887-github-io
markdown_extensions:
  - def_list
nav:
  - IssueCollector:
    - 소개: IssueCollector/소개.md
    - 개발:
      - 환경: IssueCollector/개발/환경.md