site_name: 삽질하는 고슴도치
theme:
  name: material
  language: kr
  features:
    - tabs
  palette:
    scheme: slate
  markdown_extensions:
    - toc:
        permalink: true

nav:
  - reference:
    - start: reference/index.md
    - test1: reference/test1.md
  - docker:
    - portainer: docker/portainer.md
    - MkDocs: docker/Material for MkDocs.md